### ISSUE TITLE
Allow to use pre-installed FTXUI instead of always building a duplicate

### ISSUE THREAD

**Issue by barracuda156** [BrianAnakPintar/step-writer#1]
@BrianAnakPintar `FTXUI` is available as a port: https://ports.macports.org/port/FTXUI
Could you please add an option to use external `FTXUI` if it is available and fetch it only if it is not?

**Comment by barracuda156** [comment]
P. S. And the same for `tree-sitter` and `gtest`.

**Comment by BrianAnakPintar** [comment]
Sure that sounds good, I'm not familiar with how to do that in CMake though, is it possible for you to implement it?
