### ISSUE TITLE
Minor issues with the app

### ISSUE THREAD

**Issue by barracuda156** [BrianAnakPintar/step-writer#3]
I am not sure if I do everything correctly, since I just wanted to check whether the binary works. What I noticed:

1. The app does not launch just with `step-writer`:
```
svacchanda@43-38 ~ % step-writer
Invalid arguments. Use ./step-writer <path>
```
It also does not launch with a path in fact. What works it to supply a path to a specific file. Not sure if this is intended.

2. Control + P does not return to the main menu.
3. Settings from the main menu are not clickable.

**Comment by barracuda156** [comment]
![step-writer](https://github.com/user-attachments/assets/1fce4a63-53c9-4011-882e-e940a01cc776)

**Comment by BrianAnakPintar** [comment]
In terms of these issues:
1. The app does not launch just with step-writer:
Yeah that seems like a bug, it's main intention is to be used with `./step-writer <path>` I'll work on fixing it and updating the README, thanks for notifying that.
2. Control + P does not return to the main menu:
I think I might have changed this code a while back and added some conditions to it, I'll check the code on it as well.
3. Settings from the main menu are not clickable:
The settings is something I haven't implemented yet, so I'll remove it from the main menu for now. 

Thanks again for noticing and raising these issues. I really appreciate your help.

**Comment by barracuda156** [comment]
@BrianAnakPintar BTW I got it running now on an old PowerMac:

![step-writer](https://github.com/user-attachments/assets/2902e9f4-69e6-462a-8414-c29781b78bac)

**Comment by BrianAnakPintar** [comment]
Nice!!
Thanks for the help again! It means a lot to me.

**Comment by barracuda156** [comment]
@BrianAnakPintar Merged to MacPorts now: https://ports.macports.org/port/step-writer
